// export const interests = [
//   'JavaScript',
//   'HTML',
//   'CSS',
//   'HTML5',
//   'CSS3',
//   'JQuery',
//   'Database',
//   'MongoDB',
//   'SQL',
//   'Blockchain',
//   'Cryptocurrency',
//   'Metaverse',
//   'Dating',
// ]
// export const interests = [
//   { id: 1, name: 'JavaScript', value: 'javascript' },
//   { id: 2, name: 'HTML', value: 'html' },
//   { id: 3, name: 'CSS', value: 'css' },
//   { id: 4, name: 'HTML5', value: 'html5' },
//   { id: 5, name: 'CSS3', value: 'css3' },
//   { id: 6, name: 'JQuery', value: 'jquery' },
//   { id: 7, name: 'Database', value: 'database' },
//   { id: 8, name: 'MongoDB', value: 'mongodb' },
//   { id: 9, name: 'SQL', value: 'sql' },
//   { id: 10, name: 'Blockchain', value: 'blockchain' },
//   { id: 11, name: 'Cryptocurrency', value: 'cryptocurrency' },
//   { id: 12, name: 'Metaverse', value: 'metaverse' },
//   { id: 13, name: 'Dating', value: 'dating' },
// ]

export const interests = [
  'Technology',
  'Programming',
  'Web Development',
  'Software',
  'JavaScript',
  'React',
  'Node.js',
  'Python',
  'Java',
  'C++',
  'HTML',
  'CSS',
  'Design',
  'User Experience',
  'Mobile Apps',
  'iOS Development',
  'Android Development',
  'Machine Learning',
  'Artificial Intelligence',
  'Data Science',
  'Blockchain',
  'JavaScript',
  'HTML',
  'CSS',
  'HTML5',
  'CSS3',
  'JQuery',
  'Database',
  'MongoDB',
  'SQL',
  'Blockchain',
  'Cryptocurrency',
  'Metaverse',
  'Dating',
  'Cryptocurrency',
  'Security',
  'Cloud Computing',
  'DevOps',
  'Database',
  'SQL',
  'NoSQL',
  'IoT',
  'Augmented Reality',
  'Virtual Reality',
  'Gaming',
  'UI/UX',
  'Startup',
  'Entrepreneurship',
  'Productivity',
  'Agile',
  'Scrum',
  'Git',
  'Open Source',
  'Linux',
  'Windows',
  'MacOS',
  'Networking',
  'Algorithms',
  'Data Structures',
  'Testing',
  'Performance',
  'Frameworks',
  'Libraries',
  'Blogging',
  'Content Marketing',
  'Social Media',
  'SEO',
  'Digital Marketing',
  'E-commerce',
  'Fintech',
  'Healthcare',
  'Education',
  'Travel',
  'Food',
  'Photography',
  'Art',
  'Music',
  'Books',
  'Movies',
  'Fitness',
  'Wellness',
  'Self-Improvement',
  'Personal Development',
  'Career',
  'Finance',
  'Investing',
  'Real Estate',
  'Science',
  'Space',
  'Environment',
  'History',
  'Philosophy',
  'Politics',
  'Sustainability',
  'Culture',
  'Society',
  'Parenting',
  'Relationships',
  'Pets',
  'Fashion',
  'Beauty',
  'Lifestyle',
  'Sports',
  'Gardening',
  'Cooking',
  'DIY',
  'Crafts',
  'Hobbies',
  'Travel Tips',
  'Photography Tips',
  'Life Hacks',
  'Inspiration',
  'Motivation',
  'Tutorials',
  'How-To',
  'Interviews',
  'Case Studies',
  'Dating',
  'AI',
  'Big Data',
  'Cloud Computing',
  'Cybersecurity',
  'Data Science',
  'DevOps',
  'E-commerce',
  'Hardware',
  'Internet of Things (IoT)',
  'Machine Learning',
  'Mobile Development',
  'Software Development',
  'Entrepreneurship',
  'Finance',
  'Marketing',
  'Management',
  'Personal Finance',
  'Sales',
  'Startups',
  'Strategy',
  'Productivity',
  'Leadership',
  'Cooking',
  'Fashion',
  'Fitness',
  'Food',
  'Health',
  'Home Improvement',
  'Travel',
  'Parenting',
  'Relationships',
  'Self-Improvement',
  'Arts',
  'Culture',
  'Education',
  'Environment',
  'Games',
  'News',
  'Politics',
  'Religion',
  'Science',
  'Sports',
  'Travel',
  'Adventure',
  'Exploration',
  'Culture',
  'Memories',
  'Reading',
  'Books',
  'Literature',
  'Imagination',
  'Knowledge',
  'Fashion',
  'Style',
  'Trends',
  'Self-expression',
  'Creativity',
  'JavaScript',
  'Programming',
  'Web Development',
  'Basic Operations',
  'Code Snippets',
  'coding',
  'python',
  'javascript',
  'html',
  'css',
  'django',
  'flask',
  'react',
  'angular',
  'vue',
  'machine learning',
  'artificial intelligence',
  'natural language processing',
  'data science',
  'devops',
  'cloud computing',
  'web development',
  'software engineering',
  'product management',
  'marketing',
  'business',
  'design',
  'photography',
  'travel',
  'lifestyle',
  'health',
  'fitness',
  'food',
  'parenting',
  'self-help',
  'productivity',
  'creativity',
  'travel',
  'books',
  'movies',
  'music',
  'games',
  'sports',
  'culture',
  'politics',
  'current events',
  'news',
  'python',
  'javascript',
  'html',
  'css',
  'django',
  'flask',
  'react',
  'angular',
  'vue',
  'machine learning',
  'artificial intelligence',
  'natural language processing',
  'data science',
  'devops',
  'cloud computing',
  'web development',
  'software engineering',
  'product management',
  'marketing',
  'business',
  'design',
  'photography',
  'travel',
  'lifestyle',
  'health',
  'fitness',
  'food',
  'parenting',
  'self-help',
  'productivity',
  'creativity',
  'travel',
  'books',
  'movies',
  'music',
  'games',
  'sports',
  'culture',
  'politics',
  'current events',
  'news',
  'coding',
  'programming',
  'development',
  'learning',
  'tutorial',
  'guide',
  'tips',
  'tricks',
  'best practices',
  'beginner',
  'intermediate',
  'advanced',
  'expert',
  'free',
  'open source',
  'community',
  'forum',
  'chat',
  'support',
  'documentation',
  'tutorial',
  'blog',
  'podcast',
  'video',
  'article',
  'whitepaper',
  'case study',
  'research',
  'conference',
  'meetup',
  'hackathon',
  'workshop',
  'career',
  'education',
  'job',
  'internship',
  'scholarship',
  'grant',
  'fellowship',
  'startup',
  'business',
  'marketing',
  'sales',
  'product',
  'design',
  'devops',
  'cloud',
  'security',
  'compliance',
  'data',
  'analytics',
  'science',
  'engineering',
  'research',
  'artificial intelligence',
  'machine learning',
  'natural language processing',
  'computer vision',
  'robotics',
  'drones',
  'virtual reality',
  'augmented reality',
  'blockchain',
  'cryptocurrency',
  'web development',
  'software development',
  'full stack',
  'front end',
  'back end',
  'devops',
  'cloud',
  'mobile',
  'game development',
  'design',
  'ux',
  'ui',
  'photography',
  'videography',
  'travel',
  'lifestyle',
  'health',
  'fitness',
  'food',
  'parenting',
  'self-help',
  'productivity',
  'creativity',
  'books',
  'movies',
  'music',
  'games',
  'sports',
  'culture',
  'politics',
  'current events',
  'news',
  'Financial Aid',
  'Opportunities',
  'future',
  'Security',
  'Cybersecurity',
  'Online Safety',
  'Data Protection',
  'sales',
  'sales techniques',
  'sales tips',
  'closing deals',
  'customer service',
  'Politics',
  'Governance',
  'Society',
  'Public Policy',
  'Political Dynamics',
  'Monkeypox',
  'Inflation',
  'War in Ukraine',
  'Climate Change',
  'Supply Chain',
  'Cryptocurrency',
  'Metaverse',
  'NFT',
  'Web3',
  'War',
]
